BASE: ['']
TOOLBOX_MODE: "only_test"  # "train_and_test"  or "only_test"
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: False
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/content/drive/MyDrive/research_project/data/UBFC-rPPG/test_data_150_1"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/content/drive/MyDrive/research_project/data/UBFC-rPPG/test_data_150_1"    # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "/content/drive/MyDrive/research_project/data/UBFC-rPPG/test_data_150_1_preprocess/DataFileLists1/" 
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['DiffNormalized']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128                 #only support for factor of 512
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESTORE:
        DO_RESTORE: True
      RESIZE:
        H: 126
        W: 126
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: /content/drive/MyDrive/research_project/runs/exp/200_1_swinir
MODEL:
  DROP_RATE: 0.2
  NAME: Physnet
  PHYSNET:
    FRAME_NUM: 128
    DO_RESTORE: True
    SWINIR_MODEL_PATH: "/content/drive/MyDrive/research_project/experiments/pretrained_models/006_colorCAR_DFWB_s126w7_SwinIR-M_jpeg40.pth"
    FREEZE_SWINIR: True
    FREEZE_PHYSNET: True
INFERENCE:
  BATCH_SIZE: 1
  EVALUATION_METHOD: FFT        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: "./final_model_release/PURE_PhysNet_DiffNormalized.pth"
